/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { VoteCandidate } from "./VoteCandidate";

export { Ownable__factory } from "./factories/Ownable__factory";
export { VoteCandidate__factory } from "./factories/VoteCandidate__factory";
